import type { PersonalityProfile } from './types';

const allAxes = {
  chaos: 50,
  slack: 50,
  mask: 50,
  please: 50,
  broke: 50,
  impulse: 50,
};

const weightCore = {
  chaos: 1.1,
  slack: 1.1,
  mask: 1,
  please: 1,
  broke: 1,
  impulse: 1,
};

const profile = (
  value: Omit<PersonalityProfile, 'axisWeights'> & { axisWeights?: PersonalityProfile['axisWeights'] },
): PersonalityProfile => ({
  ...value,
  axisWeights: value.axisWeights ?? weightCore,
});

export const personalities: PersonalityProfile[] = [
  profile({
    code: 'IMSB',
    nameZh: '自我攻击者',
    faction: 'meme',
    tagline: '你的嘴是自动火力系统，优先锁定的永远是你自己。',
    summary: '你把自我攻击做成了日更栏目，像在脑内开发布会，主题永远是“这锅我背”。',
    deepDive: {
      overview: '你不是单纯悲观，你是在抢首评。只要现实还没开口，你就先用最狠版本定义自己，图一个“至少我早就知道”。',
      trigger: '别人一句普通反馈、一次小失误、一个没回你的消息，都能被你翻译成“我果然不行”的全网通稿。',
      socialPattern: '你擅长把崩溃包装成段子，让场子先热起来；等所有人笑完，你再独自收拾那点被你剪碎的自尊。',
      copingTip: '先别做人格判决，改做事故报告。把“我烂透了”换成“这次我晚了 20 分钟，因为昨晚 3 点才睡”，你会立刻少掉一半自损伤害。',
    },
    targetScores: { ...allAxes, chaos: 74, slack: 61, mask: 68, please: 79, broke: 56, impulse: 41 },
    recipeKey: 'imsB',
    quote: '你不是在反省，你是在给自己开无限连的批斗会。',
  }),
  profile({
    code: 'BOSS',
    nameZh: '领导者',
    faction: 'role',
    tagline: '你不是领导者，你是人形总控台，空气一乱你就想给宇宙拉流程图。',
    summary: '你的人生底层逻辑是“失控=事故”。你很会扛局、救火、收口，能把一地鸡毛压成可执行清单；但代价是你连放空都要先立项，连崩溃都想走审批流。',
    deepDive: {
      overview: '你不是爱管，你是把秩序当氧气吸。别人看到你像定海神针，讲话稳、动作准、决策快；你自己体感却像在同时盯八块监控屏: 进度、质量、情绪、风险、预算、关系、后果和锅要谁背。你最怕的不是难，是“没人收口还在假装没事”，那会让你大脑瞬间拉响红色警报，启动一级战备模式。',
      trigger: '你的触发器非常具体也非常离谱: 群里三小时没人拍板、文档写了像没写、同一件事被说出五个版本、对方回你“再看看吧”、会议结束只有情绪没有结论。以上任意一项出现，你脑内就会弹出系统通知: “检测到混沌扩散，建议立即接管指挥权，否则 23:47 全员在工位上演灾难片续集”。',
      socialPattern: '你在人群里的存在感像“默认队长”: 大家会下意识等你定节奏，出问题先看你脸色，甚至把“你来一句”当作流程最后一步。高配版本的你很有安全感，像混乱场景里的防抖器；低配版本的你压强极高，像自带 deadline 的人形扩音器，别人会配合你，但也会把真实疲惫、真实异议和真实边界先藏起来，避免被你当场归档成“待优化项”。',
      copingTip: '你要练的不是“更会控”，而是“可控地放手”。先从三个动作开始: 第一，把“我来做”改成“我定标准+你交版本”; 第二，把“我盯全过程”改成“我只看两个关键节点”; 第三，在开场就说清楚“失误可修复，但信息黑箱不行”。你真正的王炸不是永远亲自下场救火，而是你不在场时，系统依旧能跑、团队依旧敢说、事情依旧不崩。',
    },
    targetScores: { ...allAxes, chaos: 28, slack: 19, mask: 62, please: 24, broke: 33, impulse: 26 },
    recipeKey: 'boss',
    quote: '你不是天生想当总指挥，你只是见过太多“没人负责”把小事炸成大型事故现场。',
  }),
  profile({
    code: 'MUM',
    nameZh: '妈妈',
    faction: 'role',
    tagline: '你会照顾所有人，除了那个已经快空掉的自己。',
    summary: '你天然进入照顾者模式，擅长善后、安抚和兜底，但经常把自己排最后。',
    deepDive: {
      overview: '你把被需要感当作价值来源，久而久之很难停止输出。',
      trigger: '只要看到别人失控、委屈或无助，你就会自动接管情绪劳动。',
      socialPattern: '别人会依赖你，甚至把你的温柔默认为默认服务。',
      copingTip: '把照顾频率从“默认全开”调成“按情况开启”，不是谁都值得。',
    },
    targetScores: { ...allAxes, chaos: 38, slack: 35, mask: 54, please: 86, broke: 45, impulse: 33 },
    recipeKey: 'mum',
    quote: '你不是慈母光环，你是被长期透支的情绪外包部门。',
  }),
  profile({
    code: 'FAKE',
    nameZh: '伪人',
    faction: 'meme',
    tagline: '你最强的超能力，是把自己营业成一个没有漏洞的人。',
    summary: '你非常知道什么场合该说什么话、露什么表情，但真实感常常被你自己藏起来。',
    deepDive: {
      overview: '你靠精密的社会面具通关现实，稳定却也疏离。',
      trigger: '面对权威、陌生环境和评价风险时，你的营业人格会立刻上线。',
      socialPattern: '别人觉得你体面、礼貌、没毛病，真正靠近你却不容易。',
      copingTip: '试着在低风险关系里暴露一点真实偏好，让自己不只剩下“适配”。',
    },
    targetScores: { ...allAxes, chaos: 36, slack: 42, mask: 92, please: 58, broke: 49, impulse: 28 },
    recipeKey: 'fake',
    quote: '你没在撒谎，你只是把全部真相都裁掉了。',
  }),
  profile({
    code: 'DEAD',
    nameZh: '死者',
    faction: 'nihilist',
    tagline: '你的肉身在线，灵魂显示“离开工位，稍后回来”。',
    summary: '你不是躺平，你是系统低电量保护: 功能还在，但每个动作都像在拖着 300 斤空气前进。',
    deepDive: {
      overview: '你现在像一台开了二十个后台程序的旧手机，不是不能用，是一点开新任务就发烫卡死。麻木不是性格，是过载后的省电协议。',
      trigger: '连续高压、社交超载、睡眠欠债会把你一键切到“我已去世但还能回复收到”的模式，连情绪都开始走简装版。',
      socialPattern: '别人看你很淡定，你自己知道那叫掉帧。你不是没有感觉，是感觉加载太慢，慢到外界以为你早就看开了。',
      copingTip: '先别讨论人生意义，先把电量充到 30%。吃饭、睡觉、晒太阳、少接一件事，这些看似无聊的小动作，比任何热血宣言都更像真正的复活术。',
    },
    targetScores: { ...allAxes, chaos: 22, slack: 94, mask: 33, please: 30, broke: 64, impulse: 21 },
    recipeKey: 'dead',
    quote: '你不是废了，你只是被生活按成了省电模式。',
  }),
  profile({
    code: 'ZZZZ',
    nameZh: '装死者',
    faction: 'nihilist',
    tagline: '不是问题解决了，是你暂时从问题的视野里消失了。',
    summary: '你偏爱失联、潜水和假装没看见，因为这是你最熟练的自保手段。',
    deepDive: {
      overview: '你擅长通过降低存在感来规避压力，本质上是典型的回避型求生。',
      trigger: '任何需要明确回应、承担后果、处理关系张力的场景都会让你想隐身。',
      socialPattern: '你经常让人觉得“怎么突然不见了”，但这通常不是恶意。',
      copingTip: '从最小回复开始练习，例如只发一句确认，不要等到必须解释。',
    },
    targetScores: { ...allAxes, chaos: 31, slack: 89, mask: 59, please: 42, broke: 52, impulse: 24 },
    recipeKey: 'zzzz',
    quote: '逃避没有让生活变简单，只是把战场往后拖了。',
  }),
  profile({
    code: 'GOGO',
    nameZh: '行者',
    faction: 'original',
    tagline: '人还在路上，心已经先开始念“继续走”。',
    summary: '你属于边崩边赶路型人格，不一定真的有答案，但你会继续往前拱。',
    deepDive: {
      overview: '你靠行动维持精神连续性，停下来反而更容易听见内耗。',
      trigger: '感到无意义时，你会本能地找下一件能推进的事。',
      socialPattern: '别人会觉得你很能扛，但不一定知道你其实也常靠惯性活着。',
      copingTip: '保留行动优势，同时给自己留一点停顿，不必把移动当麻醉。',
    },
    targetScores: { ...allAxes, chaos: 47, slack: 24, mask: 41, please: 39, broke: 44, impulse: 46 },
    recipeKey: 'gogo',
    quote: '你不是不累，你只是还没允许自己停。',
  }),
  profile({
    code: 'FUCK',
    nameZh: '草者',
    faction: 'rager',
    tagline: '你是情绪化身，一点就着，着了还会继续长。',
    summary: '你对荒谬现实的耐受阈值很低，但生命力很强，属于边破防边野蛮生长。',
    deepDive: {
      overview: '你不擅长压住情绪，所有不爽都会长出草来，从头顶扎出去。',
      trigger: '被糊弄、被规训、被迫装正常时，你的怒气会成倍上升。',
      socialPattern: '你可能让人觉得冲，但也因为足够真，所以很难彻底被忽略。',
      copingTip: '把爆炸从“即时外放”调成“延迟十分钟外放”，你会少很多后悔。',
    },
    targetScores: { ...allAxes, chaos: 93, slack: 41, mask: 18, please: 16, broke: 39, impulse: 89 },
    recipeKey: 'fuck',
    quote: '你不是脾气差，你是对荒谬容忍度过低。',
  }),
  profile({
    code: 'CTRL',
    nameZh: '拿捏者',
    faction: 'meme',
    tagline: '你喜欢稳稳控住局面，最好连别人的情绪也一并控住。',
    summary: '你很清楚什么叫“可控”，也很擅长用技巧和判断维持上风。',
    deepDive: {
      overview: '你依赖计划、判断和节奏感，让自己远离被动。',
      trigger: '一旦感到不可控，你会迅速加强管理、介入和修正。',
      socialPattern: '别人会觉得你很可靠，也会在你身上感到一点难以亲近的锋利。',
      copingTip: '允许一小部分事情不在掌控内，别把控制当唯一安全感来源。',
    },
    targetScores: { ...allAxes, chaos: 34, slack: 21, mask: 58, please: 34, broke: 30, impulse: 22 },
    recipeKey: 'ctrl',
    quote: '你最擅长的不是安排事情，是安排自己不失控。',
  }),
  profile({
    code: 'HHHH',
    nameZh: '傻乐者',
    faction: 'meme',
    tagline: '人生虽然离谱，但你先笑了再说。',
    summary: '你把笑当作缓冲垫，用一种看似没心没肺的方式跨过很多尴尬和难受。',
    deepDive: {
      overview: '你靠情绪转译生存，能把很多本该难堪的瞬间转成乐子。',
      trigger: '越尴尬、越荒唐、越超出理解范围，你越容易笑出声。',
      socialPattern: '你是群体里很好的气氛修复器，但别人也可能忽略你的认真时刻。',
      copingTip: '笑可以保命，但也留一点空间给真实情绪，不用永远接梗。',
    },
    targetScores: { ...allAxes, chaos: 62, slack: 42, mask: 29, please: 45, broke: 43, impulse: 67 },
    recipeKey: 'hhhh',
    quote: '你不是不痛，只是会先把痛翻译成笑点。',
  }),
  profile({
    code: 'SEXY',
    nameZh: '尤物',
    faction: 'meme',
    tagline: '你的人设感很强，而且你知道这件事。',
    summary: '你对魅力、氛围和被看见有天然敏感度，懂得经营存在感。',
    deepDive: {
      overview: '你擅长通过风格、姿态和语言调动场域，让自己成为焦点。',
      trigger: '需要展现吸引力、争取关注、抢回掌控感时，你的表现力会明显增强。',
      socialPattern: '别人容易被你吸引，也容易把你误解成单纯在表演。',
      copingTip: '经营魅力不是问题，但别让“被看见”成为唯一价值证明。',
    },
    targetScores: { ...allAxes, chaos: 54, slack: 34, mask: 57, please: 31, broke: 27, impulse: 71 },
    recipeKey: 'sexy',
    quote: '你把存在感穿在身上，走到哪都自带一点滤镜。',
  }),
  profile({
    code: 'OJBK',
    nameZh: '无所谓人',
    faction: 'nihilist',
    tagline: '不是佛，是彻底懒得跟世界较劲。',
    summary: '你对很多事都能说“都行”，不是因为包容，而是因为懒得再投入情绪。',
    deepDive: {
      overview: '你已经把松弛练成了一种钝感，很多波动在你这里直接被消音。',
      trigger: '连续失望之后，你会快速进入“无所谓，随便吧”的保护壳。',
      socialPattern: '别人会觉得你好说话，但其实你只是降低了参与感。',
      copingTip: '适度无所谓很好，但别把真实需求也一起放弃。',
    },
    targetScores: { ...allAxes, chaos: 17, slack: 81, mask: 26, please: 29, broke: 48, impulse: 29 },
    recipeKey: 'ojbk',
    quote: '你不是豁达，你只是懒得再起波澜。',
  }),
  profile({
    code: 'POOR',
    nameZh: '贫穷者',
    faction: 'role',
    tagline: '你的生活管理哲学，通常从“先看看余额”开始。',
    summary: '你对资源匮乏极度敏感，既现实又疲惫，总在算精神和钱包还能撑多久。',
    deepDive: {
      overview: '你非常清楚生活的成本，因此很多选择都被现实先过滤一遍。',
      trigger: '价格、时间、精力消耗一旦超标，你会立刻退回保守模式。',
      socialPattern: '别人会觉得你务实甚至拧巴，但你只是知道余量不多。',
      copingTip: '别把所有“我想要”都自动判成“不配”，偶尔也给欲望留点预算。',
    },
    targetScores: { ...allAxes, chaos: 44, slack: 57, mask: 41, please: 47, broke: 94, impulse: 31 },
    recipeKey: 'poor',
    quote: '你不是抠，是太熟悉资源不够的恐惧。',
  }),
  profile({
    code: 'OH-NO',
    nameZh: '哦不人',
    faction: 'rager',
    tagline: '世界还没真塌，你已经先替它预演完了。',
    summary: '你是高敏预警器，擅长第一时间察觉风险，也擅长把风险脑补到最大。',
    deepDive: {
      overview: '你对负面可能性极其敏锐，常常提前进入崩溃准备态。',
      trigger: '任何不确定信息、迟来的回复、模糊语气都会让你自动解读为坏事。',
      socialPattern: '你容易让周围人感觉到紧张，但也因此经常先一步避坑。',
      copingTip: '在宣布末日之前，先列三个同样合理但没那么糟的解释。',
    },
    targetScores: { ...allAxes, chaos: 81, slack: 49, mask: 44, please: 58, broke: 51, impulse: 72 },
    recipeKey: 'ohno',
    quote: '你不是悲观，你是灾难预演能力过于发达。',
  }),
  profile({
    code: 'MONK',
    nameZh: '僧人',
    faction: 'original',
    tagline: '别人靠发疯活着，你靠强行心如止水续命。',
    summary: '你有明显的自我克制倾向，哪怕外面一地鸡毛，也会先把自己收回来。',
    deepDive: {
      overview: '你会主动降噪、抽离、收心，是少数还能在混乱里找静气的人。',
      trigger: '环境越吵、关系越乱，你越倾向于往内收，靠自我秩序自救。',
      socialPattern: '别人会觉得你稳，但也可能误会你距离感强、不够热络。',
      copingTip: '克制是优点，但别让自己变成只会忍耐的高配静音模式。',
    },
    targetScores: { ...allAxes, chaos: 19, slack: 37, mask: 35, please: 42, broke: 36, impulse: 12 },
    recipeKey: 'monk',
    quote: '你的平静不是天生，是长期自训出来的技能。',
  }),
  profile({
    code: 'SHIT',
    nameZh: '狗屎人',
    faction: 'meme',
    tagline: '你总有一种“怎么又轮到我”的命运质感。',
    summary: '你不是一直倒霉，但总能精准撞上让人翻白眼的小概率事件。',
    deepDive: {
      overview: '你对自己运气的评价极低，久而久之甚至开始预设一切都不会太顺。',
      trigger: '计划被打断、努力没回报、日常被小事折损时，你会迅速确认“果然如此”。',
      socialPattern: '你常用黑色幽默讲自己的惨事，让倒霉先变成段子。',
      copingTip: '别把几次糟糕体验写成总命运，你值得重新统计样本。',
    },
    targetScores: { ...allAxes, chaos: 59, slack: 46, mask: 34, please: 38, broke: 61, impulse: 53 },
    recipeKey: 'shit',
    quote: '你不是命差，你只是倒霉时特别会被自己记住。',
  }),
  profile({
    code: 'THAN-K',
    nameZh: '感恩者',
    faction: 'role',
    tagline: '哪怕被生活踹了一脚，你也会下意识说谢谢。',
    summary: '你有很强的礼貌和体面惯性，容易把忍耐、美化和理解别人当作本能。',
    deepDive: {
      overview: '你很擅长维持和平，但和平常常是靠你多消化一点换来的。',
      trigger: '面对权威、帮助、情感交换时，你特别容易进入感谢和回报模式。',
      socialPattern: '你通常显得懂事、温和、识大体，也因此容易被额外索取。',
      copingTip: '感谢可以保留，但不用把每一次消耗都包装成应该。',
    },
    targetScores: { ...allAxes, chaos: 24, slack: 39, mask: 62, please: 91, broke: 42, impulse: 21 },
    recipeKey: 'thank',
    quote: '你很会感恩，但不代表所有给予都值得原谅。',
  }),
  profile({
    code: 'MALO',
    nameZh: '吗喽',
    faction: 'role',
    tagline: '你知道自己在搬砖，也知道这砖今天还得继续搬。',
    summary: '你是高压打工现实的具象化，执行力在线，但尊严常常只剩一点点。',
    deepDive: {
      overview: '你对系统和秩序有很强适应力，因为不适应就活不下去。',
      trigger: '绩效、排期、任务堆积、层层传话会迅速点亮你的社畜底色。',
      socialPattern: '你很容易成为那个“再辛苦一下”的人，因为你通常真会做。',
      copingTip: '别只优化忍耐能力，也要优化退出和拒绝的能力。',
    },
    targetScores: { ...allAxes, chaos: 57, slack: 28, mask: 63, please: 69, broke: 73, impulse: 37 },
    recipeKey: 'malo',
    quote: '你不是天生能扛，是环境把你训练成了耐压件。',
  }),
  profile({
    code: 'ATM-er',
    nameZh: '送钱者',
    faction: 'role',
    tagline: '你一边心疼，一边还是把资源递了出去。',
    summary: '你在人情、消费和责任面前很容易多付出一点，最后把自己榨得很干。',
    deepDive: {
      overview: '你经常扮演供给者角色，钱、时间和情绪都是你的可支配资源。',
      trigger: '别人开口、关系升温、局面需要有人兜底时，你很难完全不出手。',
      socialPattern: '你看起来大方仗义，但这种仗义常伴随事后懊悔。',
      copingTip: '先问一句“我愿不愿意”，再问一句“我承不承受得起”。',
    },
    targetScores: { ...allAxes, chaos: 41, slack: 38, mask: 52, please: 88, broke: 82, impulse: 54 },
    recipeKey: 'atmer',
    quote: '你不是慈善家，你只是太难把“不给”说出口。',
  }),
  profile({
    code: 'THINK',
    nameZh: '想事者',
    faction: 'original',
    tagline: '你的脑子不会停，它只是换个角度继续转。',
    summary: '你高度内向地处理世界，思考很多、输出很少，容易在脑内形成过载。',
    deepDive: {
      overview: '你重视分析和理解，因此行动常常晚于推演，甚至晚于疲惫。',
      trigger: '遇到复杂问题和模糊关系时，你会开始高强度内心建模。',
      socialPattern: '别人可能觉得你慢热、冷静、难懂，但你只是还在处理。',
      copingTip: '思考不是问题，关键是给思考设置截止时间，别让它吞掉行动。',
    },
    targetScores: { ...allAxes, chaos: 33, slack: 47, mask: 57, please: 34, broke: 37, impulse: 18 },
    recipeKey: 'think',
    quote: '你不是反应慢，你是在脑内开了太多线程。',
  }),
  profile({
    code: 'SOLO',
    nameZh: '孤儿',
    faction: 'nihilist',
    tagline: '不是不想连接，只是一个人更省解释。',
    summary: '你天然偏向独处，在情绪混乱时尤其如此，宁可自己消化也不愿求助。',
    deepDive: {
      overview: '你把独处当作充电，也当作隔离层，久了会让关系难以进入。',
      trigger: '一旦觉得被误解、被要求、被打扰，你会明显后撤。',
      socialPattern: '你显得独立，但很多难题其实是自己默默咽下去的。',
      copingTip: '把求助降低到具体事务层面，不必一上来就交出全部内心。',
    },
    targetScores: { ...allAxes, chaos: 28, slack: 67, mask: 44, please: 19, broke: 49, impulse: 27 },
    recipeKey: 'solo',
    quote: '你不是冷，只是独处比解释更省力。',
  }),
  profile({
    code: 'LOVE-R',
    nameZh: '多情者',
    faction: 'meme',
    tagline: '你对浪漫和情绪回响的感知，永远比别人多一格。',
    summary: '你容易被氛围、关系和情绪流动打动，爱意和戏感都很足。',
    deepDive: {
      overview: '你有较高的情感投入倾向，能迅速放大心动，也能迅速受伤。',
      trigger: '被理解、被注视、被一点点偏爱时，你很容易投入真情。',
      socialPattern: '你是关系里很热烈的一方，但也容易被评价为太上头。',
      copingTip: '保留你的热烈，同时把期待说清，不要只靠脑补补全剧情。',
    },
    targetScores: { ...allAxes, chaos: 63, slack: 29, mask: 39, please: 67, broke: 36, impulse: 84 },
    recipeKey: 'lover',
    quote: '你不是恋爱脑，你只是感情收音机开得太大。',
  }),
  profile({
    code: 'WOC!',
    nameZh: '握草人',
    faction: 'rager',
    tagline: '你的人生关键词之一，是“这也能发生？”',
    summary: '你常年处于被世界震惊的边缘，情绪反应快，吐槽反射更快。',
    deepDive: {
      overview: '你对荒诞现实高度敏感，惊讶、冒火和破防常常是连招。',
      trigger: '离谱新闻、低级错误、反智行为最容易把你直接推到爆点。',
      socialPattern: '你很适合当第一吐槽位，也很容易在群体里制造共鸣。',
      copingTip: '吐槽是必要的，但别让每次震惊都升级成自我损耗。',
    },
    targetScores: { ...allAxes, chaos: 86, slack: 35, mask: 23, please: 26, broke: 40, impulse: 78 },
    recipeKey: 'woc',
    quote: '你不是夸张，你只是经常比别人更早看到离谱。',
  }),
  profile({
    code: 'DRUNK',
    nameZh: '酒鬼',
    faction: 'meme',
    tagline: '你的逃生舱叫微醺，哪怕很多时候只是精神微醺。',
    summary: '你倾向于用短暂放纵和即时快感给自己续命，主打一个先麻痹再说。',
    deepDive: {
      overview: '你对压力释放的需求很强，容易借助娱乐、消费或刺激让自己脱档。',
      trigger: '连续高压、情绪空转、社交疲惫后，你很想找个出口立刻解压。',
      socialPattern: '你看起来会玩、会散场、会自我调节，但后劲并不总好受。',
      copingTip: '保留放松渠道，同时给自己准备一个不靠上头的恢复手段。',
    },
    targetScores: { ...allAxes, chaos: 69, slack: 58, mask: 32, please: 29, broke: 62, impulse: 92 },
    recipeKey: 'drunk',
    quote: '你不一定真的醉，你只是太想短暂停机。',
  }),
  profile({
    code: 'IMFW',
    nameZh: '废物',
    faction: 'nihilist',
    tagline: '你的自我评价常年低空飞行，偶尔还会俯冲。',
    summary: '你对自己要求不低，但呈现出来常常是无力、迟滞和深度挫败感。',
    deepDive: {
      overview: '你不是完全不想变好，而是已经在反复失望里把期待压得很低。',
      trigger: '目标落空、执行失败、看见别人轻松做到时，你会明显陷入废感。',
      socialPattern: '你习惯用“我不行”做免责声明，避免别人真的对你失望。',
      copingTip: '把目标从人格判断改成行为拆解，先从最小可完成动作开始。',
    },
    targetScores: { ...allAxes, chaos: 46, slack: 88, mask: 51, please: 57, broke: 66, impulse: 34 },
    recipeKey: 'imfw',
    quote: '你不是没有价值，你只是长期处在自我否定的雾里。',
  }),
  profile({
    code: 'NPC',
    nameZh: '路人甲',
    faction: 'original',
    tagline: '你总能把自己隐藏得刚刚好，像系统默认值一样安全。',
    summary: '你擅长低存在感生存，不抢风头、不惹麻烦，也很少主动制造波澜。',
    deepDive: {
      overview: '你在很多场景里选择无害化表达，以降低摩擦和被关注的概率。',
      trigger: '环境复杂、人际密度高、评价风险上升时，你会更倾向于背景化。',
      socialPattern: '你经常被认为稳定、普通、很好相处，但也容易被忽略。',
      copingTip: '安全感重要，但偶尔也让自己拥有一点名字和轮廓。',
    },
    targetScores: { ...allAxes, chaos: 27, slack: 49, mask: 79, please: 63, broke: 45, impulse: 22 },
    recipeKey: 'npc',
    quote: '你不是没个性，你只是太会把自己调成默认模式。',
  }),
  profile({
    code: 'WIFI',
    nameZh: '断联者',
    faction: 'original',
    tagline: '你的精神状态像弱网，能连上，但不稳定。',
    summary: '你情绪和注意力常常忽强忽弱，容易在人际和任务中出现掉线感。',
    deepDive: {
      overview: '你并非故意失联，而是系统时常卡顿，连接欲和执行力都不恒定。',
      trigger: '消息轰炸、任务并发、关系压力会迅速把你推入“无信号”状态。',
      socialPattern: '别人可能觉得你忽冷忽热，但你自己也常对这种掉线束手无策。',
      copingTip: '把掉线前兆外化成规则，例如延迟回复模板和固定回连时间。',
    },
    targetScores: { ...allAxes, chaos: 64, slack: 72, mask: 55, please: 46, broke: 41, impulse: 63 },
    recipeKey: 'wifi',
    quote: '你不是不想连上世界，你只是经常没有满格信号。',
  }),
  profile({
    code: 'HEAL',
    nameZh: '疗愈师',
    faction: 'original',
    tagline: '你想救人，也想救自己，只是两件事经常纠缠在一起。',
    summary: '你对修复关系和修复情绪有天然兴趣，温柔但并不完全轻松。',
    deepDive: {
      overview: '你善于感受和回应他人的痛点，也容易把别人的伤拿来练自己的成熟。',
      trigger: '看到破碎、冲突、失控的人和关系时，你会本能想修补。',
      socialPattern: '你常被视为有安全感的人，但真正难受时不一定知道该向谁靠。',
      copingTip: '疗愈别人之前，先确认自己不是在透支式共情。',
    },
    targetScores: { ...allAxes, chaos: 29, slack: 33, mask: 34, please: 74, broke: 38, impulse: 26 },
    recipeKey: 'heal',
    quote: '你能安抚很多人，但也别忘了把安抚留给自己。',
  }),
  profile({
    code: 'YOLO',
    nameZh: '浪命者',
    faction: 'original',
    tagline: '计划可以明天写，今天先把这口气活爽一点。',
    summary: '你偏爱即时体验和快速反馈，不一定鲁莽，但确实很难长期憋着自己。',
    deepDive: {
      overview: '你依赖鲜活感来确认自己真的在活，因此对乏味和规训耐受度低。',
      trigger: '一旦感到日子过得像复制粘贴，你会非常想做点出格的事。',
      socialPattern: '你给周围人带来刺激和故事，也带来一定不可预测性。',
      copingTip: '保留你的生命力，但给冲动留一个预算上限和后悔缓冲带。',
    },
    targetScores: { ...allAxes, chaos: 77, slack: 37, mask: 21, please: 23, broke: 58, impulse: 96 },
    recipeKey: 'yolo',
    quote: '你不想被生活温水煮熟，所以总想先翻出锅沿。',
  }),
];

export const personalityMap: Record<string, PersonalityProfile> = Object.fromEntries(personalities.map((item) => [item.code, item]));


