import type { CharacterRecipe } from './types';

const palettes = {
  moss: {
    skin: '#f1d2b4',
    skinShadow: '#d5b18e',
    outfit: '#5d8b58',
    outfitShadow: '#3d6640',
    accent: '#8bbf47',
    accentSoft: '#dfeec4',
    hair: '#46514c',
    hairShadow: '#2d3530',
  },
  clay: {
    skin: '#f0d0b5',
    skinShadow: '#d4b08d',
    outfit: '#c07b55',
    outfitShadow: '#8e573d',
    accent: '#f1c56c',
    accentSoft: '#f8e8be',
    hair: '#3f3e43',
    hairShadow: '#232228',
  },
  ash: {
    skin: '#e9ddd0',
    skinShadow: '#c6b9ab',
    outfit: '#8e968f',
    outfitShadow: '#666d68',
    accent: '#d9dfda',
    accentSoft: '#eef2ef',
    hair: '#4b4f50',
    hairShadow: '#323637',
  },
  plum: {
    skin: '#f2d4c8',
    skinShadow: '#d6b29f',
    outfit: '#935aa5',
    outfitShadow: '#6c3f7c',
    accent: '#d8707f',
    accentSoft: '#f4d4dd',
    hair: '#3b3346',
    hairShadow: '#271f30',
  },
  neon: {
    skin: '#f6d6be',
    skinShadow: '#dcb495',
    outfit: '#3f434d',
    outfitShadow: '#252a34',
    accent: '#8ddf50',
    accentSoft: '#dbf4b7',
    hair: '#7bc746',
    hairShadow: '#559232',
  },
  sand: {
    skin: '#efd7bf',
    skinShadow: '#d1b293',
    outfit: '#b99d73',
    outfitShadow: '#8d7655',
    accent: '#d9c39a',
    accentSoft: '#f2ead9',
    hair: '#54493d',
    hairShadow: '#352d26',
  },
  rose: {
    skin: '#f5d6c7',
    skinShadow: '#d8b19d',
    outfit: '#ca4955',
    outfitShadow: '#993541',
    accent: '#f07f96',
    accentSoft: '#ffd5df',
    hair: '#50383f',
    hairShadow: '#342028',
  },
  aqua: {
    skin: '#f2d3bf',
    skinShadow: '#d7b094',
    outfit: '#4c89a5',
    outfitShadow: '#2f6079',
    accent: '#59ccb7',
    accentSoft: '#cff4eb',
    hair: '#44515c',
    hairShadow: '#29323b',
  },
  gold: {
    skin: '#f0d4b8',
    skinShadow: '#d3af8e',
    outfit: '#c7a14a',
    outfitShadow: '#997734',
    accent: '#ffe08b',
    accentSoft: '#fff1bf',
    hair: '#53412a',
    hairShadow: '#362818',
  },
  monochrome: {
    skin: '#e9dfd3',
    skinShadow: '#c3b7aa',
    outfit: '#5d646d',
    outfitShadow: '#3c4249',
    accent: '#a7b0b9',
    accentSoft: '#edf0f3',
    hair: '#3b3d42',
    hairShadow: '#232529',
  },
} satisfies Record<string, CharacterRecipe['palette']>;

export const characterRecipes: Record<string, CharacterRecipe> = {
  imsB: { skeleton: 'leaning', pose: 'slouch', palette: palettes.sand, accessories: ['messy-hair'], expression: 'sad' },
  boss: { skeleton: 'standing', pose: 'swagger', palette: palettes.gold, accessories: ['cap'], expression: 'stern' },
  mum: { skeleton: 'standing', pose: 'crossed', palette: palettes.moss, accessories: ['baby'], expression: 'soft' },
  fake: {
    skeleton: 'special',
    pose: 'neutral',
    palette: palettes.moss,
    accessories: ['mask-face'],
    expression: 'blank',
    overrideRenderer: 'fake',
  },
  dead: {
    skeleton: 'special',
    pose: 'fallen',
    palette: palettes.ash,
    accessories: ['coffin'],
    expression: 'sleep',
    overrideRenderer: 'dead',
  },
  zzzz: {
    skeleton: 'special',
    pose: 'fallen',
    palette: palettes.moss,
    accessories: ['leaf-blanket'],
    expression: 'sleep',
    overrideRenderer: 'zzzz',
  },
  gogo: { skeleton: 'standing', pose: 'neutral', palette: palettes.sand, accessories: ['walking-stick'], expression: 'blank' },
  fuck: { skeleton: 'standing', pose: 'neutral', palette: palettes.neon, accessories: ['grass-hair'], expression: 'angry' },
  ctrl: { skeleton: 'standing', pose: 'crossed', palette: palettes.aqua, accessories: ['headband'], expression: 'smirk' },
  hhhh: { skeleton: 'standing', pose: 'swagger', palette: palettes.plum, accessories: ['open-mouth'], expression: 'smirk' },
  sexy: { skeleton: 'standing', pose: 'swagger', palette: palettes.rose, accessories: ['heart-hair'], expression: 'smirk' },
  ojbk: { skeleton: 'standing', pose: 'neutral', palette: palettes.sand, accessories: ['ok-hand'], expression: 'blank' },
  poor: { skeleton: 'leaning', pose: 'slouch', palette: palettes.ash, accessories: ['torn-bag'], expression: 'sad' },
  ohno: { skeleton: 'standing', pose: 'panic', palette: palettes.clay, accessories: ['panic-hands'], expression: 'panic' },
  monk: { skeleton: 'standing', pose: 'meditate', palette: palettes.gold, accessories: ['beads'], expression: 'soft' },
  shit: { skeleton: 'standing', pose: 'neutral', palette: palettes.aqua, accessories: ['office-shirt'], expression: 'stern' },
  thank: { skeleton: 'standing', pose: 'crossed', palette: palettes.plum, accessories: ['prayer-hands'], expression: 'soft' },
  malo: { skeleton: 'standing', pose: 'panic', palette: palettes.gold, accessories: ['monkey-tail'], expression: 'sad' },
  atmer: {
    skeleton: 'special',
    pose: 'offering',
    palette: palettes.sand,
    accessories: ['cash'],
    expression: 'blank',
    overrideRenderer: 'atmer',
  },
  think: { skeleton: 'standing', pose: 'slouch', palette: palettes.monochrome, accessories: ['big-head'], expression: 'stern' },
  solo: { skeleton: 'standing', pose: 'neutral', palette: palettes.monochrome, accessories: ['hoodie'], expression: 'sad' },
  lover: {
    skeleton: 'special',
    pose: 'swagger',
    palette: palettes.rose,
    accessories: ['heart-glasses'],
    expression: 'smirk',
    overrideRenderer: 'lover',
  },
  woc: { skeleton: 'standing', pose: 'panic', palette: palettes.clay, accessories: ['burst-hair'], expression: 'panic' },
  drunk: { skeleton: 'leaning', pose: 'slouch', palette: palettes.gold, accessories: ['bottle'], expression: 'smirk' },
  imfw: { skeleton: 'standing', pose: 'slouch', palette: palettes.ash, accessories: ['trash-crown'], expression: 'sad' },
  npc: { skeleton: 'standing', pose: 'neutral', palette: palettes.monochrome, accessories: ['name-tag'], expression: 'blank' },
  wifi: { skeleton: 'standing', pose: 'panic', palette: palettes.aqua, accessories: ['signal'], expression: 'panic' },
  heal: { skeleton: 'standing', pose: 'crossed', palette: palettes.moss, accessories: ['leaf-staff'], expression: 'soft' },
  yolo: { skeleton: 'standing', pose: 'swagger', palette: palettes.plum, accessories: ['spark'], expression: 'smirk' },
};
