import type { CharacterRecipe } from './types';

const palettes = {
  moss: {
    skin: '#f1d2b4',
    skinShadow: '#d5b18e',
    outfit: '#5d8b58',
    outfitShadow: '#3d6640',
    accent: '#8bbf47',
    accentSoft: '#dfeec4',
    hair: '#46514c',
    hairShadow: '#2d3530',
  },
  clay: {
    skin: '#f0d0b5',
    skinShadow: '#d4b08d',
    outfit: '#c07b55',
    outfitShadow: '#8e573d',
    accent: '#f1c56c',
    accentSoft: '#f8e8be',
    hair: '#3f3e43',
    hairShadow: '#232228',
  },
  ash: {
    skin: '#e9ddd0',
    skinShadow: '#c6b9ab',
    outfit: '#8e968f',
    outfitShadow: '#666d68',
    accent: '#d9dfda',
    accentSoft: '#eef2ef',
    hair: '#4b4f50',
    hairShadow: '#323637',
  },
  plum: {
    skin: '#f2d4c8',
    skinShadow: '#d6b29f',
    outfit: '#935aa5',
    outfitShadow: '#6c3f7c',
    accent: '#d8707f',
    accentSoft: '#f4d4dd',
    hair: '#3b3346',
    hairShadow: '#271f30',
  },
  neon: {
    skin: '#f6d6be',
    skinShadow: '#dcb495',
    outfit: '#3f434d',
    outfitShadow: '#252a34',
    accent: '#8ddf50',
    accentSoft: '#dbf4b7',
    hair: '#7bc746',
    hairShadow: '#559232',
  },
  sand: {
    skin: '#efd7bf',
    skinShadow: '#d1b293',
    outfit: '#b99d73',
    outfitShadow: '#8d7655',
    accent: '#d9c39a',
    accentSoft: '#f2ead9',
    hair: '#54493d',
    hairShadow: '#352d26',
  },
  rose: {
    skin: '#f5d6c7',
    skinShadow: '#d8b19d',
    outfit: '#ca4955',
    outfitShadow: '#993541',
    accent: '#f07f96',
    accentSoft: '#ffd5df',
    hair: '#50383f',
    hairShadow: '#342028',
  },
  aqua: {
    skin: '#f2d3bf',
    skinShadow: '#d7b094',
    outfit: '#4c89a5',
    outfitShadow: '#2f6079',
    accent: '#59ccb7',
    accentSoft: '#cff4eb',
    hair: '#44515c',
    hairShadow: '#29323b',
  },
  gold: {
    skin: '#f0d4b8',
    skinShadow: '#d3af8e',
    outfit: '#c7a14a',
    outfitShadow: '#997734',
    accent: '#ffe08b',
    accentSoft: '#fff1bf',
    hair: '#53412a',
    hairShadow: '#362818',
  },
  monochrome: {
    skin: '#e9dfd3',
    skinShadow: '#c3b7aa',
    outfit: '#5d646d',
    outfitShadow: '#3c4249',
    accent: '#a7b0b9',
    accentSoft: '#edf0f3',
    hair: '#3b3d42',
    hairShadow: '#232529',
  },
} satisfies Record<string, CharacterRecipe['palette']>;

export const characterRecipes: Record<string, CharacterRecipe> = {
  imsB: { skeleton: 'biped', pose: 'clutch', palette: palettes.sand, accessories: ['messy-hair', 'self-arrow'], expression: 'cry' },
  boss: { skeleton: 'biped', pose: 'preach', palette: palettes.gold, accessories: ['cap', 'pointer-stick'], expression: 'stern' },
  mum: { skeleton: 'biped', pose: 'clutch', palette: palettes.moss, accessories: ['baby', 'dark-circles'], expression: 'soft' },
  fake: {
    skeleton: 'prop-heavy',
    pose: 'strut',
    palette: palettes.moss,
    accessories: ['mask-face', 'split-face'],
    expression: 'smirk',
    overrideRenderer: 'fake',
  },
  dead: {
    skeleton: 'scene',
    pose: 'coffin',
    palette: palettes.ash,
    accessories: ['coffin'],
    expression: 'sleep',
    overrideRenderer: 'dead',
  },
  zzzz: {
    skeleton: 'scene',
    pose: 'bagged',
    palette: palettes.moss,
    accessories: ['sleeping-bag'],
    expression: 'sleep',
    overrideRenderer: 'zzzz',
  },
  gogo: { skeleton: 'biped', pose: 'march', palette: palettes.sand, accessories: ['walking-stick', 'speed-dust'], expression: 'stern' },
  fuck: { skeleton: 'prop-heavy', pose: 'march', palette: palettes.neon, accessories: ['grass-hair', 'weed-arm'], expression: 'angry', overrideRenderer: 'fuck' },
  ctrl: { skeleton: 'biped', pose: 'preach', palette: palettes.aqua, accessories: ['headband', 'control-strings'], expression: 'greedy' },
  hhhh: { skeleton: 'biped', pose: 'lounge', palette: palettes.plum, accessories: ['drool', 'cheek-blush'], expression: 'drool' },
  sexy: { skeleton: 'biped', pose: 'strut', palette: palettes.rose, accessories: ['heart-hair', 'fan'], expression: 'greedy' },
  ojbk: { skeleton: 'biped', pose: 'lounge', palette: palettes.sand, accessories: ['ok-hand', 'shrug-cloud'], expression: 'blank' },
  poor: { skeleton: 'biped', pose: 'collapse', palette: palettes.ash, accessories: ['torn-bag', 'empty-bowl'], expression: 'cry' },
  ohno: { skeleton: 'biped', pose: 'panic', palette: palettes.clay, accessories: ['panic-hands', 'alarm-lines'], expression: 'panic' },
  monk: { skeleton: 'biped', pose: 'meditate', palette: palettes.gold, accessories: ['beads', 'aura-ring'], expression: 'soft' },
  shit: { skeleton: 'biped', pose: 'stumble', palette: palettes.aqua, accessories: ['office-shirt', 'poop-cloud'], expression: 'dizzy' },
  thank: { skeleton: 'prop-heavy', pose: 'pray', palette: palettes.plum, accessories: ['prayer-hands', 'thick-tears'], expression: 'cry', overrideRenderer: 'thank' },
  malo: { skeleton: 'biped', pose: 'march', palette: palettes.gold, accessories: ['monkey-tail', 'brick-load'], expression: 'sad' },
  atmer: {
    skeleton: 'prop-heavy',
    pose: 'offer',
    palette: palettes.sand,
    accessories: ['cash', 'coin-rain'],
    expression: 'greedy',
    overrideRenderer: 'atmer',
  },
  think: { skeleton: 'biped', pose: 'clutch', palette: palettes.monochrome, accessories: ['big-head', 'thought-cloud'], expression: 'stern' },
  solo: { skeleton: 'biped', pose: 'lounge', palette: palettes.monochrome, accessories: ['hoodie', 'void-shadow'], expression: 'sad' },
  lover: {
    skeleton: 'prop-heavy',
    pose: 'strut',
    palette: palettes.rose,
    accessories: ['heart-glasses', 'bouquet'],
    expression: 'greedy',
    overrideRenderer: 'lover',
  },
  woc: { skeleton: 'biped', pose: 'panic', palette: palettes.clay, accessories: ['burst-hair', 'shock-burst'], expression: 'panic' },
  drunk: { skeleton: 'biped', pose: 'stumble', palette: palettes.gold, accessories: ['bottle', 'spill'], expression: 'dizzy' },
  imfw: { skeleton: 'biped', pose: 'collapse', palette: palettes.ash, accessories: ['trash-crown', 'white-flag'], expression: 'cry' },
  npc: { skeleton: 'biped', pose: 'float', palette: palettes.monochrome, accessories: ['name-tag', 'dialog-box'], expression: 'blank' },
  wifi: { skeleton: 'biped', pose: 'panic', palette: palettes.aqua, accessories: ['signal', 'loading-ring'], expression: 'dizzy' },
  heal: { skeleton: 'biped', pose: 'offer', palette: palettes.moss, accessories: ['leaf-staff', 'bandage-heart'], expression: 'soft' },
  yolo: { skeleton: 'biped', pose: 'strut', palette: palettes.plum, accessories: ['spark', 'firework'], expression: 'manic' },
};
